name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write
    steps:
      # 1. checkout 時に output ブランチを指定し、TOKENを渡す
      - uses: actions/checkout@v4
        with:
          ref: output
          token: ${{ secrets.PROFILE_TOKEN }}

      # 2. カード生成アクションの実行
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ${{ github.repository_owner }}
          UTC_OFFSET: 9
          BRANCH_NAME: output
          AUTO_PUSH: true
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}